Gracefully handles version and drops `version` suffix
ember-cli/broccoli-middleware pull request #27
Opened 2017-06-11 20:45 UTC by twokul

2017-06-11 20:47 UTC, stefanpenner requested changes

2017-06-11 20:47 UTC, stefanpenner commented on lib/templates/error.html
> +          {{#if broccoliBuilderVersion}}broccoli-builder@{{broccoliBuilderVersion}}{{/if}}{{#if nodeJSVersion}}, node@{{nodeJSVersion}}{{/if}}
we should likely do this programmatically, and sorted alphabetically

2017-06-12 15:09 UTC, rwjblue approved these changes

2017-06-12 15:12 UTC, stefanpenner approved these changes

2017-06-12 15:12 UTC, merged