Add test harness in broccoli-middleware repo
ember-cli/broccoli-middleware pull request #8
Opened 2016-11-21 01:04 UTC by kratiahuja

This PR primarily addresses this [issue](https://github.com/ember-cli/broccoli-middleware/issues/7)

Adds 3 basic tests:
- [x] Basic file serving test
- [x] Error when file not found
- [x] Error when watcher is rejected

cc: @stefanpenner

2016-11-21 01:06 UTC, kratiahuja commented
aah test failing because of `class`. Will switch to old school way. 

Should I also add code coverage?

2016-11-21 01:15 UTC, kratiahuja commented
Going to add some more tests.

2016-11-21 01:56 UTC, kratiahuja commented
Added enough tests for all basic functionality of this middleware.

2016-11-21 02:02 UTC, kratiahuja commented
@stefanpenner This should be ready to be merged. I will add code coverage tool in another PR to isolate the changes and make it easy for review.

2016-11-21 03:00 UTC, stefanpenner requested changes
Largely looks good, left some comments. Once addressed this should be mergable.

2016-11-21 03:00 UTC, stefanpenner commented on test/middleware-test.js
> +          done();
rather then using `done`, which if an assertion before it fails (like line 42) will cause the test to timeout. Lets use mocha's build in promise support.

Simply return a promise in the `it` `function`, like:

```js
it('foo', function() {
  return server.start().then(...);
});
```

If the promise rejects, the test fails, if the promise fulfills the test passes.

2016-11-21 03:00 UTC, stefanpenner commented on test/middleware-test.js
> +      server.start()
return the promise, rather then using `done`

2016-11-21 03:00 UTC, stefanpenner commented on test/middleware-test.js
> +        })
return the promise rather then using done

2016-11-21 03:00 UTC, stefanpenner commented on test/middleware-test.js
> +          done();
return the promise rather then using done

2016-11-21 03:00 UTC, stefanpenner commented on test/middleware-test.js
> +        .then(function() {
`.catch`

2016-11-21 03:00 UTC, stefanpenner commented on test/middleware-test.js
> +      watcher = new RSVP.Promise(function(resolve, reject) {
A simpler way to describe this is:

```js
RSVP.Promise.reject({ stack: '..' , broccoliPayload: '..' })
```

2016-11-21 03:02 UTC, stefanpenner commented
It looks like travis is enabled, do you mind adding the badge to the readme? I believe it is:

```md
[![Build Status](https://travis-ci.org/ember-cli/broccoli-middleware.svg?branch=master)](https://travis-ci.org/ember-cli/broccoli-middleware)
```

2016-11-21 03:03 UTC, stefanpenner commented
appveyor badge is:

```
[![Build status](https://ci.appveyor.com/api/projects/status/p4kvoah8x88dvwjo/branch/master?svg=true)](https://ci.appveyor.com/project/embercli/broccoli-middleware/branch/master)
```

also just enabled appveyor 👍

2016-11-21 07:55 UTC, kratiahuja commented
@stefanpenner Thanks for the feedback. I totally forgot about the promise API of mocha 😄 . I have fixed. 

One thing I noticed is the image for appveyor seems to be broken. Not sure if the link is correct or not.

2016-11-21 07:55 UTC, kratiahuja commented on test/middleware-test.js
> +          done();
Fixed.

2016-11-21 07:58 UTC, kratiahuja commented on test/middleware-test.js
> +        .then(function() {
Fixed.

2016-11-21 07:58 UTC, kratiahuja commented on test/middleware-test.js
> +      watcher = new RSVP.Promise(function(resolve, reject) {
Fixed

2016-11-21 17:42 UTC, stefanpenner approved these changes

2016-11-21 17:43 UTC, stefanpenner commented
> One thing I noticed is the image for appveyor seems to be broken. Not sure if the link is correct or not.

Ah, ill fix it.

This looks great!

2016-11-21 17:43 UTC, merged

2016-11-21 17:44 UTC, stefanpenner commented
@kratiahuja the badge seems to work, it may have been an appveyor glitch yesterday. They had some issue.

2016-11-21 19:38 UTC, kratiahuja commented
Aah ok didn't realize something was broken there.

2016-11-25 08:40 UTC, Turbo87 commented on test/middleware-test.js
> +    it('responds with error if file not found', function(done) {
@kratiahuja unfortunately this doesn't really work. A test function must not use the `done` callback and return a `Promise` at the same time (see #13).

I tried changing it to the following, but it didn't seem to resolve properly:

```js
    it('responds with error if file not found', function() {
      var deferred = RSVP.defer();

      watcher['builder']['outputPath'] = fixture('basic-file');
      var middleware = broccoliMiddleware(watcher, {
        autoIndex: false
      });

      var wrapperMiddleware = function(req, resp /*next*/) {
        return middleware(req, resp, function(err) {
          expect(resp.finished).to.be.false;
          expect(err.message).to.have.string('ENOENT');
          deferred.resolve();
        })
      };
      server = new TestHTTPServer(wrapperMiddleware);

      return server.start().then(function(info) {
        return server.request('/non-existent-file', {
          info: info
        });
      }).then(function() {
        return deferred.promise;
      });
    });
```

2016-11-25 21:06 UTC, kratiahuja commented on test/middleware-test.js
> +    it('responds with error if file not found', function(done) {
@Turbo87 : That's interesting. I am surprised how CI didn't catch it earlier unless mocha added that assertion in a later version. 

I'll debug and see if I can fix it.

2016-11-25 21:37 UTC, kratiahuja commented on test/middleware-test.js
> +    it('responds with error if file not found', function(done) {
@Turbo87 : Attempt to fix it in a straightforward way : #14

2016-11-25 23:16 UTC, Turbo87 commented on test/middleware-test.js
> +    it('responds with error if file not found', function(done) {
Yes, they introduced that assertion in 3.0